[tool.poetry]
authors = ["Gabe Joseph <gjoseph92@gmail.com>"]
description = "Load a STAC collection into xarray with dask"
license = "MIT"
name = "stackstac"
readme = "README.md"
repository = "https://github.com/gjoseph92/stackstac"
homepage = "https://stackstac.readthedocs.io/en/latest/index.html"
version = "0.1.1"

[tool.poetry.dependencies]
python = "^3.8"
dask = {extras = ["array"], version = "^2021.4.1"}
numpy = "^1.20.0"
pyproj = "^3.0.0"
rasterio = "^1.2.3"
xarray = "^0.17.0"
Sphinx = {version = "^3.5.4", optional = true}
numpydoc = {version = "^1.1.0", optional = true}
pandoc = {version = "^1.0.2", optional = true}
insipid-sphinx-theme = {version = "^0.2.3", optional = true}
nbsphinx = {version = "^0.8.2", optional = true}
sphinx-autodoc-typehints = {version = "^1.11.1", optional = true}
ipython = {version = "^7.20.0", optional = true}
coiled = {version = "^0.0.38", optional = true}
distributed = {version = "^2021.4.1", optional = true}
matplotlib = {version = "^3.4.1", optional = true}
sat-search = {version = "^0.3.0", optional = true}
pystac-client = {version = "^0.1.1", optional = true}
planetary-computer = {version = "^0.1.0", optional = true}
ipyleaflet = {version = "^0.13.6", optional = true}
jupyterlab-geojson = {version = "^3.1.2", optional = true}
dask-labextension = {version = "^5.0.1", optional = true}
Bottleneck = {version = "^1.3.2", optional = true}
jupyter-sphinx = {version = "^0.3.2", optional = true}
geogif = {version = "^0.1.0", optional = true}

[tool.poetry.dev-dependencies]
Pympler = "^0.9"
awkward = {version = "^1.1.2", allow-prereleases = true}
black = "^21.4b2"
debugpy = "^1.2.1"
filprofiler = "^0.17.0"
flake8 = "^3.9.1"
jupyterlab = "^3.0.14"
py-spy = "^0.3.4"
snakeviz = "^2.1.0"
sphinx-autobuild = "^2021.3.14"
twine = "^3.4.1"
keyring = "^23.0.1"

[tool.poetry.extras]
docs = [
  "Sphinx",
  "numpydoc",
  "sphinx-autodoc-typehints",
  "pandoc",
  "nbsphinx",
  "insipid-sphinx-theme",
  "ipython",
  "jupyter-sphinx"
]
binder = [
  "coiled",
  "distributed",
  "matplotlib",
  "sat-search",
  "pystac-client",
  "planetary-computer",
  "ipyleaflet",
  "jupyterlab-geojson",
  "dask-labextension",
  "Bottleneck",
  "geogif",
]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
