[tool.poetry]
authors = ["Gabe Joseph <gjoseph92@gmail.com>"]
description = "Load a STAC collection into xarray with dask"
license = "MIT"
name = "stackstac"
readme = "README.md"
repository = "https://github.com/gjoseph92/stackstac"
homepage = "https://stackstac.readthedocs.io/en/latest/index.html"
version = "0.1.1"

[tool.poetry.dependencies]
python = "^3.7"
dask = {extras = ["array"], version = "^2021.2.0"}
numpy = "^1.20.0"
pyproj = "^3.0.0"
rasterio = "^1.2.0"
xarray = "^0.17.0"
Sphinx = {version = "^3.5.2", optional = true}
numpydoc = {version = "^1.1.0", optional = true}
pandoc = {version = "^1.0.2", optional = true}
insipid-sphinx-theme = {version = "^0.2.3", optional = true}
nbsphinx = {version = "^0.8.2", optional = true}
sphinx-autodoc-typehints = {version = "^1.11.1", optional = true}
ipython = {version = "^7.20.0", optional = true}

[tool.poetry.dev-dependencies]
Pympler = "^0.9"
awkward = {version = "^1.1.2", allow-prereleases = true}
black = "^20.8b1"
coiled = "^0.0.36"
debugpy = "^1.2.1"
distributed = "^2021.2.0"
filprofiler = "^0.17.0"
flake8 = "^3.8.4"
jupyterlab = "^3.0.7"
matplotlib = "^3.3.4"
py-spy = "^0.3.4"
pystac = "^0.5.4"
sat-search = "^0.3.0"
sat-stac = "^0.4.1"
snakeviz = "^2.1.0"
sphinx-autobuild = "^2020.9.1"
twine = "^3.4.1"
keyring = "^23.0.1"

[tool.poetry.extras]
docs = [
  "Sphinx",
  "numpydoc",
  "sphinx-autodoc-typehints",
  "pandoc",
  "nbsphinx",
  "insipid-sphinx-theme",
  "ipython",
]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
